config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :admin_users, param: :uid do
    resources :adoption_requests, except: [:new, :create], controller: 'admin_users/adoption_requests'
    resources :approved_adoption_requests, only: [:create], controller: 'admin_users/approved_adoption_requests'
  end
  resources :users, param: :uid do
    resources :adoption_requests, only: [:index, :new, :create], controller: 'users/adoption_requests'
    resources :kitten_requests, only: [:index, :new, :create], controller: 'users/kitten_requests'
  end

  # resources :adoption_requests, except: [:new, :create]
  mount RailsEventStore::Browser => '/res' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_uid

  def to_param
    uid
  end

  private

  def generate_uid
    self.uid = SecureRandom.uuid
  end
end

app/controllers/users/adoption_requests_controller.rb
module Users
  class AdoptionRequestsController < ApplicationController
    def index
      @requests = AdoptionRequest.where(requester: params[:user_uid]).to_a
    end

    def new
      @request_id = SecureRandom.uuid
      @requester_id = params[:user_uid]
    end

    def create
      bus.(Waiting::RequestAcceptance.new(request_id: params[:request_id], color: params[:color], requester: params[:requester_id]))
      redirect_to "/users/#{params[:requester_id]}", notice: 'Thank you. We will get back you soon.'
    end
  end
end

app/controllers/users/kitten_requests_controller.rb
module Users
  class KittenRequestsController < ApplicationController
    def index
      @requests = KittenRequest.where(requester: params[:user_uid])
    end

    def new
      @request_id = SecureRandom.uuid
      @requester_id = params[:user_uid]
    end

    def create
      bus.(Adoption::RequestKitten.new(request_id: params[:request_id], color: params[:color], requester: params[:requester_id]))
      redirect_to "/users/#{params[:requester_id]}", notice: 'Thank you. Your request accepted.'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by!(uid: params[:uid])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :uid)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.uid %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'New Adoption Request', new_user_adoption_request_path(@user) %> |
<%= link_to 'Your Adoption Requests', user_adoption_requests_path(@user) %> |
<%= link_to 'New Kitten Requests', new_user_kitten_request_path(@user) %> |
<%= link_to 'Your Kitten Requests', user_kitten_requests_path(@user) %>