config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :admin_users, param: :uid do
    resources :adoption_requests, except: [:new, :create], controller: 'admin_users/adoption_requests'
    resources :approved_adoption_requests, only: [:create], controller: 'admin_users/approved_adoption_requests'
  end
  resources :users, param: :uid do
    resources :adoption_requests, only: [:index, :new, :create], controller: 'users/adoption_requests'
    resources :kitten_requests, only: [:index, :new, :create], controller: 'users/kitten_requests'
  end

  # resources :adoption_requests, except: [:new, :create]
  mount RailsEventStore::Browser => '/res' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/query/deal.rb
module Query
  class Deal < ApplicationRecord
    def state
      self[:state].to_sym
    end

    def self.on_deal_started
      lambda do |event|
        create!(uid: event.data[:deal_id], adoption_request_id: event.data[:adoption_request_id], kitten_request_id: event.data[:kitten_request_id], state: :negotiating)
      end
    end

    def self.on_deal_closed
      lambda do |event|
        find_by!(uid: event.data[:deal_id]).update!(state: :closed)
      end
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deal_params
      params.require(:deal).permit(:adoption_request_id, :kitten_request_id, :state)
    end
end

app/views/deals/_form.html.erb
<%= form_with(model: deal, local: true) do |form| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
        <% deal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :adoption_request_id %>
    <%= form.text_field :adoption_request_id %>
  </div>

  <div class="field">
    <%= form.label :kitten_request_id %>
    <%= form.text_field :kitten_request_id %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deals</h1>

<table>
  <thead>
    <tr>
      <th>Adoption request</th>
      <th>Kitten request</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= deal.adoption_request_id %></td>
        <td><%= deal.kitten_request_id %></td>
        <td><%= deal.state %></td>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adoption request:</strong>
  <%= @deal.adoption_request_id %>
</p>

<p>
  <strong>Kitten request:</strong>
  <%= @deal.kitten_request_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @deal.state %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>