config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :admin_users, param: :uid do
    resources :adoption_requests, except: [:new, :create], controller: 'admin_users/adoption_requests'
    resources :approved_adoption_requests, only: [:create], controller: 'admin_users/approved_adoption_requests'
  end
  resources :users, param: :uid do
    resources :adoption_requests, only: [:index, :new, :create], controller: 'users/adoption_requests'
    resources :kitten_requests, only: [:index, :new, :create], controller: 'users/kitten_requests'
  end

  # resources :adoption_requests, except: [:new, :create]
  mount RailsEventStore::Browser => '/res' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  before_create :generate_uid

  def to_param
    uid
  end

  private

  def generate_uid
    self.uid = SecureRandom.uuid
  end
end

app/controllers/admin_users/adoption_requests_controller.rb
module AdminUsers
  class AdoptionRequestsController < ApplicationController
    def index
      @requests = AdoptionRequest.all.to_a
    end

    def new
      @request_id = SecureRandom.uuid
      @requester_id = params[:user_uid]
    end

    def create
      bus.(Waiting::RequestAcceptance.new(request_id: params[:request_id], color: params[:color], requester: params[:requester_id]))
      redirect_to "/users/#{params[:requester_id]}", notice: 'Thank you. We will get back you soon.'
    end
  end
end

app/controllers/admin_users/approved_adoption_requests_controller.rb
module AdminUsers
  class ApprovedAdoptionRequestsController < ApplicationController
    def create
      bus.(Waiting::ApproveRequest.new(request_id: params[:request_id], approver: params[:admin_user_uid]))
      redirect_to "/admin_users/#{params[:admin_user_uid]}/adoption_requests", notice: "request: #{params[:request_id]} is approved"
    end
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin_users
  # GET /admin_users.json
  def index
    @admin_users = AdminUser.all
  end

  # GET /admin_users/1
  # GET /admin_users/1.json
  def show
  end

  # GET /admin_users/new
  def new
    @admin_user = AdminUser.new
  end

  # GET /admin_users/1/edit
  def edit
  end

  # POST /admin_users
  # POST /admin_users.json
  def create
    @admin_user = AdminUser.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'Admin user was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin_users/1
  # PATCH/PUT /admin_users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'Admin user was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin_users/1
  # DELETE /admin_users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'Admin user was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = AdminUser.find_by!(uid: params[:uid])
    end

    # Only allow a list of trusted parameters through.
    def admin_user_params
      params.require(:admin_user).permit(:name, :uid)
    end
end

app/views/admin_users/_form.html.erb
<%= form_with(model: admin_user, local: true) do |form| %>
  <% if admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
        <% admin_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.name %></td>
        <td><%= admin_user.uid %></td>
        <td><%= link_to 'Show', admin_user %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
        <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin User', new_admin_user_path %>

app/views/admin_users/new.html.erb
<h1>New Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_user.name %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @admin_user.uid %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %> |
<%= link_to 'Approve Requests', "/admin_users/#{@admin_user.uid}/adoption_requests" %>